# Generated by Django 3.0.6 on 2020-06-24 05:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityperiod',
            name='user_fk',
        ),
        migrations.AddField(
            model_name='activityperiod',
            name='User',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='testapp.User'),
            preserve_default=False,
        ),
    ]
