# Generated by Django 3.0.6 on 2020-06-24 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20200624_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityperiod',
            old_name='User',
            new_name='user',
        ),
    ]
