# Generated by Django 3.0.6 on 2020-06-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20200624_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
